name: learning trigger type Issuse
on:
  issues:
    types:
      - opened
      - opened
      - edited
      - deleted
      - closed
      - reopened
      - labeled
      - unlabeled
      - assigned
      - unassigned
      - milestoned
      - demilestoned
      - pinned
      - unpinned
      - locked
      - unlocked
      - transferred
jobs:
  Amal_learning_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Learning issues
      uses: actions/checkout@v4
    - name: Learning issues
      
      run: echo "Issues is working fine "

