name: learning trigger type Issuse
on:
  issues:
    types:
      - opened
      - opened
      - edited
      - deleted
      - closed
      - reopened
      - labeled
      - unlabeled
      - assigned
      - unassigned
      - milestoned
      - demilestoned
      - pinned
      - unpinned
      - locked
      - unlocked
      - transferred
  workflow_dispatch:
     inputs:
       environment:
         description:  "Enter Environment"
         required: true
         default: "dev"   
       version:
         description: "Enter version"
         required: true
         default: "dev"
jobs:
  Amal_learning_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Learning issues
      uses: actions/checkout@v4
    - name: Learning issues
      
      run: |
        echo "Issues is working fine "
        echo "Environment: ${{ inputs.environment }}"
        echo "Version: ${{ inputs.version }}"

