name: learning scheudle Job cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  Amal_learning:
    runs-on: ubuntu-latest
    steps:
      - name: Amal_Learning
        run: |
          echo "Welcome to Secheudle"