name: learning scheudle Job cron
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  Amal_learning:
    runs-on: ubuntu-latest
    steps:
      - name: Actions
        uses: actions/checkout@v4
      - name: Amal_Learning
        run: |
          echo "Welcome to Secheudle"
          echo "Amal is  schedule CRON Job" 